conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from ikwen.flatpages.views import FlatPageView
from ikwen.core.views import DefaultHome

from website.views import Kakocase, PinsView, About, Terms


from ikwen_foulassi.foulassi.views import EventList

from dbbackup.views import Home

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'^$', DefaultHome.as_view(), name='home'),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^retail/', include('ikwen.partnership.urls', namespace='partnership')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    url(r'^shavida/', include('ikwen_shavida.shavida.urls', namespace='shavida')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^kakocase/', Kakocase.as_view(), name='kakocase'),
    url(r'^pinsview/', PinsView.as_view(), name='pinsview'),
    url(r'^about/', About.as_view(), name='about'),
    url(r'^terms/', Terms.as_view(), name='terms_and_conditions'),
    url(r'^webnode/', include('ikwen_webnode.webnode.urls', namespace='webnode')),
    url(r'^daraja/', include('daraja.urls', namespace='daraja')),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^', include('dbbackup.urls', namespace='dbbackup')),
)

dbbackup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import permission_required, login_required

from dbbackup.views import ChangeJobConfig, Home, JobConfigList, BackupList, test_db_connection,\
    test_destination_server_connection  # , JobConfigView
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^jobConfigurationList$', permission_required("dbbackup.ik_setup_jobs")(JobConfigList.as_view()), name='jobconfig_list'),
    url(r'^jobConfig$', permission_required("dbbackup.ik_setup_jobs")(ChangeJobConfig.as_view()), name='change_jobconfig'),
    url(r'^jobConfig/(?P<object_id>[-\w]+)$', permission_required("dbbackup.ik_setup_jobs")(ChangeJobConfig.as_view()), name='change_jobconfig'),
    url(r'^backupList$', permission_required("dbbackup.ik_manage_backups")(BackupList.as_view()), name='backup_list'),
    url(r'^backupList/(?P<object_id>[-\w]+)$', permission_required("dbbackup.ik_manage_backups")(BackupList.as_view()), name='backup_list'),
    url(r'^dbServerValidation$', permission_required("dbbackup.ik_manage_backups")(test_db_connection), name='test_db_connection'),
    url(r'^destinationServerValidation$', permission_required("dbbackup.ik_manage_backups")(test_destination_server_connection), name='test_destination_server_connection'),

)

templates/core/app_base_admin.html
{% extends 'core/base_admin.html' %}
{% load i18n static humanize user_agents auth_tokens media_from_provider cache %}
{% if perms.dbbackup.ik_setup_jobs or perms.dbbackup.ik_manage_backups  %}
    {% block app_admin_nav %}
        <div class="divider"></div>
        <ul class="nav nav-pills nav-stacked">
            {% if perms.dbbackup.ik_setup_jobs  %}
                <li role="presentation" class="homepage">
                    {% url 'dbbackup:jobconfig_list' as job_config_list_url %}
                    <a href="{{ job_config_list_url }}">{% trans "Job configs" %}</a>
                </li>
            {% endif %}
            {% if perms.dbbackup.ik_manage_backups  %}
                <li role="presentation" class="menus">
                    <a href="{% url 'dbbackup:backup_list' %}">
                        {% trans "Backups" %}
                    </a>
                </li>
            {% endif %}
        </ul>
    {% endblock %}
{% endif  %}